# Generated by Django 4.2.13 on 2024-06-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='basket',
            name='avito_url',
            field=models.URLField(default='#'),
        ),
    ]
