# Generated by Django 4.2.13 on 2024-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_basket_avito_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='avito_url',
        ),
        migrations.AddField(
            model_name='product',
            name='avito_url',
            field=models.URLField(default='#'),
        ),
    ]
