# Generated by Django 5.0.6 on 2024-07-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0009_product_size_alter_product_name_alter_product_price",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужское"), ("F", "Женское"), ("U", "Унисекс")],
                default="U",
                max_length=1,
            ),
        ),
    ]
