# Generated by Django 5.0.6 on 2024-07-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("?", "Unknown"),
                    ("XXS", "XXS (32)"),
                    ("XS", "XS (34)"),
                    ("S", "S (36-38)"),
                    ("M", "M (40-42)"),
                    ("L", "L (44-46)"),
                    ("XL", "XL (48)"),
                    ("XXL", "XXL (50)"),
                    ("XXXL", "XXXL (52-54)"),
                ],
                default="Unknown",
                max_length=15,
            ),
        ),
    ]
