# Generated by Django 5.0.6 on 2024-08-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="avito_url",
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужское"), ("F", "Женское")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
