# Generated by Django 5.0.6 on 2024-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0012_remove_product_avito_url_alter_product_gender_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
