# Generated by Django 5.1.6 on 2025-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("?", "Unknown"),
                    ("XXS", "XXS (38-40)"),
                    ("XS", "XS (40-42)"),
                    ("S", "S (44-46)"),
                    ("M", "M (46-48)"),
                    ("L", "L (48-50)"),
                    ("XL", "XL (50-52)"),
                    ("XXL", "XXL (52-54)"),
                    ("XXXL", "XXXL (54-56)"),
                ],
                default="Unknown",
                max_length=15,
            ),
        ),
    ]
