# Generated by Django 5.1.2 on 2025-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reservation",
            field=models.BooleanField(default=False),
        ),
    ]
