# Generated by Django 5.1.2 on 2025-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_product_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
