# Generated by Django 5.1.2 on 2025-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
